// src/hooks/useOrders.js
import { useCallback, useEffect, useState } from "react";

/**
 * useOrders (HYBRID MODE – MOCK + CAP)
  * =========================================================
   * ✔ UI-first, backend-authoritative when available
    * ✔ Auto-fallback to mock data on timeout / failure
     * ✔ Same public contract as CAP-backed hook
      * ✔ Safe for Phase-1 completion
       * =========================================================
        */

        const API_BASE = "/odata/v4/sales";

        /* =========================================================
           MOCK DATA (MASTER + CHILD)
           ========================================================= */
           const MOCK_ORDERS = [
             // -------- MASTER SOs --------
               {
                   ID: "M1",
                       orderNo: "SO1001",
                           parentSO_ID: null,
                               customer_ID: "C1",
                                   customerName: "Customer One",
                                       status: "Created",
                                           priority: 1,
                                               remarks: "Master Order 1001"
                                                 },
                                                   {
                                                       ID: "M2",
                                                           orderNo: "SO1002",
                                                               parentSO_ID: null,
                                                                   customer_ID: "C2",
                                                                       customerName: "Customer Two",
                                                                           status: "Created",
                                                                               priority: 1,
                                                                                   remarks: "Master Order 1002"
                                                                                     },

                                                                                       // -------- CHILD SOs --------
                                                                                         {
                                                                                             ID: "C1-1",
                                                                                                 orderNo: "SO1001/1",
                                                                                                     parentSO_ID: "M1",
                                                                                                         customer_ID: "C1",
                                                                                                             customerName: "Customer One",
                                                                                                                 expectedShipDate: "2025-02-10",
                                                                                                                     plant: "Plant A",
                                                                                                                         status: "Created",
                                                                                                                             priority: 1,
                                                                                                                                 currentStage: "SalesSupport"
                                                                                                                                   },
                                                                                                                                     {
                                                                                                                                         ID: "C2-1",
                                                                                                                                             orderNo: "SO1002/1",
                                                                                                                                                 parentSO_ID: "M2",
                                                                                                                                                     customer_ID: "C2",
                                                                                                                                                         customerName: "Customer Two",
                                                                                                                                                             expectedShipDate: "2025-02-12",
                                                                                                                                                                 plant: "Plant B",
                                                                                                                                                                     status: "Created",
                                                                                                                                                                         priority: 1,
                                                                                                                                                                             currentStage: "Procurement"
                                                                                                                                                                               }
                                                                                                                                                                               ];

                                                                                                                                                                               /* =========================================================
                                                                                                                                                                                  HELPER: BUILD CUSTOMER LIST
                                                                                                                                                                                  ========================================================= */
                                                                                                                                                                                  function deriveCustomers(orders = []) {
                                                                                                                                                                                    const map = new Map();
                                                                                                                                                                                      orders.forEach(o => {
                                                                                                                                                                                          if (o.customer_ID && !map.has(o.customer_ID)) {
                                                                                                                                                                                                map.set(o.customer_ID, {
                                                                                                                                                                                                        id: o.customer_ID,
                                                                                                                                                                                                                name: o.customerName || "Unknown"
                                                                                                                                                                                                                      });
                                                                                                                                                                                                                          }
                                                                                                                                                                                                                            });
                                                                                                                                                                                                                              return [...map.values()];
                                                                                                                                                                                                                              }

                                                                                                                                                                                                                              /* =========================================================
                                                                                                                                                                                                                                 HOOK IMPLEMENTATION
                                                                                                                                                                                                                                 ========================================================= */
                                                                                                                                                                                                                                 export default function useOrders() {
                                                                                                                                                                                                                                   const [orders, setOrders] = useState([]);
                                                                                                                                                                                                                                     const [customers, setCustomers] = useState([]);
                                                                                                                                                                                                                                       const [loading, setLoading] = useState(true);
                                                                                                                                                                                                                                         const [error, setError] = useState(null);

                                                                                                                                                                                                                                           /* =====================================================
                                                                                                                                                                                                                                                FETCH FROM BACKEND (WITH TIMEOUT PROTECTION)
                                                                                                                                                                                                                                                  ===================================================== */
                                                                                                                                                                                                                                                    const fetchFromBackend = useCallback(async () => {
                                                                                                                                                                                                                                                        const controller = new AbortController();
                                                                                                                                                                                                                                                            const timeout = setTimeout(() => controller.abort(), 8000); // 8s guard

                                                                                                                                                                                                                                                                try {
                                                                                                                                                                                                                                                                      const res = await fetch(`${API_BASE}/SalesOrders?$expand=customer`, {
                                                                                                                                                                                                                                                                              signal: controller.signal
                                                                                                                                                                                                                                                                                    });

                                                                                                                                                                                                                                                                                          if (!res.ok) throw new Error("Backend fetch failed");

                                                                                                                                                                                                                                                                                                const json = await res.json();
                                                                                                                                                                                                                                                                                                      const raw = Array.isArray(json?.value) ? json.value : [];

                                                                                                                                                                                                                                                                                                            const normalized = raw.map(o => ({
                                                                                                                                                                                                                                                                                                                    ID: o.ID,
                                                                                                                                                                                                                                                                                                                            orderNo: o.orderNo,
                                                                                                                                                                                                                                                                                                                                    parentSO_ID: o.parentSO?.ID ?? null,
                                                                                                                                                                                                                                                                                                                                            customer_ID: o.customer?.ID ?? null,
                                                                                                                                                                                                                                                                                                                                                    customerName: o.customer?.name ?? "Unknown",
                                                                                                                                                                                                                                                                                                                                                            expectedShipDate: o.expectedShipDate,
                                                                                                                                                                                                                                                                                                                                                                    plant: o.plant,
                                                                                                                                                                                                                                                                                                                                                                            status: o.status,
                                                                                                                                                                                                                                                                                                                                                                                    priority: o.priority ?? 1,
                                                                                                                                                                                                                                                                                                                                                                                            currentStage: o.currentStage ?? "SalesSupport",
                                                                                                                                                                                                                                                                                                                                                                                                    remarks: o.remarks
                                                                                                                                                                                                                                                                                                                                                                                                          }));

                                                                                                                                                                                                                                                                                                                                                                                                                setOrders(normalized);
                                                                                                                                                                                                                                                                                                                                                                                                                      setCustomers(deriveCustomers(normalized));
                                                                                                                                                                                                                                                                                                                                                                                                                            setError(null);
                                                                                                                                                                                                                                                                                                                                                                                                                                  return true;
                                                                                                                                                                                                                                                                                                                                                                                                                                      } catch (e) {
                                                                                                                                                                                                                                                                                                                                                                                                                                            console.warn("⚠ Backend unavailable, using mock data");
                                                                                                                                                                                                                                                                                                                                                                                                                                                  return false;
                                                                                                                                                                                                                                                                                                                                                                                                                                                      } finally {
                                                                                                                                                                                                                                                                                                                                                                                                                                                            clearTimeout(timeout);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }, []);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                    /* =====================================================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                         INITIAL LOAD (HYBRID STRATEGY)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ===================================================== */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                             useEffect(() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 (async () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       setLoading(true);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             const ok = await fetchFromBackend();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   if (!ok) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           // Fallback to mock
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   setOrders(MOCK_ORDERS);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           setCustomers(deriveCustomers(MOCK_ORDERS));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   setError("Backend slow/unavailable – running in mock mode");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               setLoading(false);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   })();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }, [fetchFromBackend]);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       /* =====================================================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            MOVE CHILD SO (UI-FIRST, BACKEND LATER)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ===================================================== */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const moveToStage = async (orderID, stage) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // UI update (optimistic but controlled)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        setOrders(prev =>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              prev.map(o =>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      o.ID === orderID ? { ...o, currentStage: stage } : o
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Fire backend call (non-blocking)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              await fetch(`${API_BASE}/requestStageTransition`, {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      method: "POST",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              headers: { "Content-Type": "application/json" },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      body: JSON.stringify({ orderID })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } catch {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      // ignore in Phase 1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              /* =====================================================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   CREATE CHILD SO (UI-FIRST)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ===================================================== */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       const createChildSO = payload => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           const { parentSO_ID, expectedShipDate, plant } = payload;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               const master = orders.find(o => o.ID === parentSO_ID);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   if (!master) return;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       const children = orders.filter(o => o.parentSO_ID === parentSO_ID);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           const nextIndex = children.length + 1;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               const child = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ID: `${parentSO_ID}-${nextIndex}`,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           orderNo: `${master.orderNo}/${nextIndex}`,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 parentSO_ID,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       customer_ID: master.customer_ID,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             customerName: master.customerName,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   expectedShipDate,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         plant,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               status: "Created",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     priority: 1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           currentStage: "SalesSupport",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 remarks: "New Child SO"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         setOrders(prev => [...prev, child]);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             // Backend call (non-blocking)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 fetch(`${API_BASE}/createChildSO`, {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       method: "POST",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             headers: { "Content-Type": "application/json" },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   body: JSON.stringify(payload)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       }).catch(() => {});
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           /* =====================================================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                PUBLIC API (STABLE CONTRACT)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ===================================================== */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        orders,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            customers,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                loading,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    error,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        moveToStage,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            createChildSO
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              